### ISSUE TITLE
WHMCS 8.x compatibility

### ISSUE THREAD

**Issue by Tampa** [WevrLabs-Group/WHMCS-Blend-Admin-Theme-Dark-Mode#4]
What's the status of this at the moment?
What areas are done/need doing?

**Comment by garousiamir** [comment]
Hi @Tampa 
I made the necessary changes to make it compatible with WHMCS 8.1
https://github.com/garousiamir/whmcs-admin-dark-theme

**Comment by WevrLabs** [comment]
> Hi @Tampa
> I made the necessary changes to make it compatible with WHMCS 8.1
> https://github.com/garousiamir/whmcs-admin-dark-theme

Thank you, @garousiamir for the great work, it looks awesome!
Can you please create a PR from your fork, so that the updates can be reflected on the main respo here?
Kind regard.

**Comment by garousiamir** [comment]
Hi @WevrLabs 
Unfortunately, since I'm not a pro user of git I made mistake, and instead of forking your repo, I made my own which I think it's now impossible to create a PR since folders are different in your repo.
Sorry for my bad. you may be able to replace my changed CSS file and put it in your repo.

**Comment by Tampa** [comment]
I looked at your repo and it seems you dumped the whole template structure in there. I think this repo only has some form of override the system then applies to the theme itself?

I tried extracting the changes in order to correlate them to this repo, but the parts are entirely different so I am not sure how that even works. Could it be that this is the old style vs. new tpl styling that was introduced a while back?

In any case, I made a pull request, but I suspect it's not the kind @WevrLabs is looking for.

**Comment by WevrLabs** [comment]
Hi @Tampa  ... Thanks for the efforts!

The implementation is a simple hook that is triggered on the admin `<head></head>` area, it pulls a CSS file that has the modifications ( `https://github.com/WevrLabs-Group/WHMCS-Blend-Admin-Theme-Dark-Mode/blob/master/assets/css/admin-dark.css` ). So, there's no actual edits happening on the theme files itself (which prevents them being overwritten on updates).

Now I haven't yet had a look at WHMCS v8.x (we tend not to upgrade to latest versions immediately, just to make sure no bugs on the way, and to ensure all current implementations we have in place in our system are ready for upgrade). As such, I have not yet had a look at v8.x 

But I guess there will be no much work, just the modifications made into the `https://github.com/WevrLabs-Group/WHMCS-Blend-Admin-Theme-Dark-Mode/blob/master/assets/css/admin-dark.css` file, the same way it is done for prior releases. I could spin up a test environment on v8, but I still haven't find time yet. But I will sure do it in the coming few weeks.

**Comment by Tampa** [comment]
I could try to diff the dark blend with the regular blend once I update my whmcs, that hopefully should give some info on what needs changing.

I like the approach of just overrides, but doesn't that make page generation slower if it has to load the theme and then override it again?

**Comment by WevrLabs** [comment]
Did not notice much difference on page load, after all, once the page is loaded for the first time, the browser then caches the files locally. However, making the compatibility with v8 is just as simple as adding CSS rules for new elements to that file, editing existing rules, etc, shouldn't be much work I guess.

**Comment by garousiamir** [comment]
Hi @Tampa  and @WevrLabs,
Yes, you are both right. as I said since I'm not a pro user of GitHub I guess I did not do the correct way of contributing.
I used the CSS WevrLabs created and put it at the end of theme.min.css in whmcs 8.1 blend theme and did some extra codes for some fixes especially for automation and setting pages also the menus have changed a bit.
But don't worry @Tampa I only add the CSS in the theme which is safe to use and there should be no problem.
Regards

**Comment by WevrLabs** [comment]
Exactly, @garousiamir ... Making adjustments for v8 is just by adding those extra CSS codes to the hook's main CSS file `/whmcpath/assets/css/admin-dark.css`. No requirement for altering or editing the theme's original files, and at the same time, avoiding these codes being overwritten in future updates.

**Comment by Tampa** [comment]
I did just test in 8.3.1 and it looks like most is working. One small enhancement I would make is trying to !important or otherwise force the ticket text color, since for some reason depending on the data sent from the email import it sets font color. Guessing the emails do some html encoding and WHMCS doesn't strip that.
